# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# This file is part of methpipe
#
# Copyright (C) 2010-2019: Andrew D. Smith
#
# Authors: Andrew D. Smith
#
# This is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.



am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/methpipe
pkgincludedir = $(includedir)/methpipe
pkglibdir = $(libdir)/methpipe
pkglibexecdir = $(libexecdir)/methpipe
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = pmd$(EXEEXT) methcounts$(EXEEXT) bsrate$(EXEEXT) \
	hmr$(EXEEXT) hypermr$(EXEEXT) levels$(EXEEXT) \
	roimethstat$(EXEEXT) methstates$(EXEEXT) methentropy$(EXEEXT) \
	hmr_rep$(EXEEXT) multimethstat$(EXEEXT) lc_approx$(EXEEXT) \
	fast-liftover$(EXEEXT) lift-filter$(EXEEXT) \
	merge-bsrate$(EXEEXT) merge-methcounts$(EXEEXT) \
	duplicate-remover$(EXEEXT) symmetric-cpgs$(EXEEXT) \
	clean-hairpins$(EXEEXT) selectsites$(EXEEXT) \
	guessprotocol$(EXEEXT) $(am__EXEEXT_1) allelicmeth$(EXEEXT) \
	amrfinder$(EXEEXT) amrtester$(EXEEXT) radmeth$(EXEEXT) \
	methdiff$(EXEEXT) dmr$(EXEEXT) mlml$(EXEEXT)
#am__append_1 = to-mr
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_cxx_compile_stdcxx.m4 \
	$(top_srcdir)/m4/ax_cxx_compile_stdcxx_11.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
#am__EXEEXT_1 = to-mr$(EXEEXT)
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
LIBRARIES = $(noinst_LIBRARIES)
AR = ar
ARFLAGS = cru
AM_V_AR = $(am__v_AR_$(V))
am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
am__v_AR_0 = @echo "  AR      " $@;
am__v_AR_1 = 
libmethpipe_a_AR = $(AR) $(ARFLAGS)
libmethpipe_a_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_libmethpipe_a_OBJECTS = src/common/BetaBin.$(OBJEXT) \
	src/common/Distro.$(OBJEXT) \
	src/common/EmissionDistribution.$(OBJEXT) \
	src/common/Epiread.$(OBJEXT) src/common/EpireadStats.$(OBJEXT) \
	src/common/LevelsCounter.$(OBJEXT) \
	src/common/MethpipeSite.$(OBJEXT) \
	src/common/Smoothing.$(OBJEXT) \
	src/common/ThreeStateHMM.$(OBJEXT) \
	src/common/TwoStateHMM.$(OBJEXT) \
	src/common/TwoStateHMM_PMD.$(OBJEXT) \
	src/common/bsutils.$(OBJEXT) \
	src/common/numerical_utils.$(OBJEXT)
libmethpipe_a_OBJECTS = $(am_libmethpipe_a_OBJECTS)
am_allelicmeth_OBJECTS = src/amrfinder/allelicmeth.$(OBJEXT)
allelicmeth_OBJECTS = $(am_allelicmeth_OBJECTS)
allelicmeth_LDADD = $(LDADD)
allelicmeth_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_amrfinder_OBJECTS = src/amrfinder/amrfinder.$(OBJEXT)
amrfinder_OBJECTS = $(am_amrfinder_OBJECTS)
amrfinder_LDADD = $(LDADD)
amrfinder_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_amrtester_OBJECTS = src/amrfinder/amrtester.$(OBJEXT)
amrtester_OBJECTS = $(am_amrtester_OBJECTS)
amrtester_LDADD = $(LDADD)
amrtester_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_bsrate_OBJECTS = src/analysis/bsrate.$(OBJEXT)
bsrate_OBJECTS = $(am_bsrate_OBJECTS)
bsrate_LDADD = $(LDADD)
bsrate_DEPENDENCIES = libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a
am_clean_hairpins_OBJECTS = src/utils/clean-hairpins.$(OBJEXT)
clean_hairpins_OBJECTS = $(am_clean_hairpins_OBJECTS)
clean_hairpins_LDADD = $(LDADD)
clean_hairpins_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_dmr_OBJECTS = src/radmeth/dmr.$(OBJEXT)
dmr_OBJECTS = $(am_dmr_OBJECTS)
dmr_LDADD = $(LDADD)
dmr_DEPENDENCIES = libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a
am_duplicate_remover_OBJECTS = src/utils/duplicate-remover.$(OBJEXT)
duplicate_remover_OBJECTS = $(am_duplicate_remover_OBJECTS)
duplicate_remover_LDADD = $(LDADD)
duplicate_remover_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_fast_liftover_OBJECTS = src/utils/fast-liftover.$(OBJEXT)
fast_liftover_OBJECTS = $(am_fast_liftover_OBJECTS)
fast_liftover_LDADD = $(LDADD)
fast_liftover_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_guessprotocol_OBJECTS = src/utils/guessprotocol.$(OBJEXT)
guessprotocol_OBJECTS = $(am_guessprotocol_OBJECTS)
guessprotocol_LDADD = $(LDADD)
guessprotocol_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_hmr_OBJECTS = src/analysis/hmr.$(OBJEXT)
hmr_OBJECTS = $(am_hmr_OBJECTS)
hmr_LDADD = $(LDADD)
hmr_DEPENDENCIES = libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a
am_hmr_rep_OBJECTS = src/analysis/hmr_rep.$(OBJEXT)
hmr_rep_OBJECTS = $(am_hmr_rep_OBJECTS)
hmr_rep_LDADD = $(LDADD)
hmr_rep_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_hypermr_OBJECTS = src/analysis/hypermr.$(OBJEXT)
hypermr_OBJECTS = $(am_hypermr_OBJECTS)
hypermr_LDADD = $(LDADD)
hypermr_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_lc_approx_OBJECTS = src/utils/lc_approx.$(OBJEXT)
lc_approx_OBJECTS = $(am_lc_approx_OBJECTS)
lc_approx_LDADD = $(LDADD)
lc_approx_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_levels_OBJECTS = src/analysis/levels.$(OBJEXT)
levels_OBJECTS = $(am_levels_OBJECTS)
levels_LDADD = $(LDADD)
levels_DEPENDENCIES = libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a
am_lift_filter_OBJECTS = src/utils/lift-filter.$(OBJEXT)
lift_filter_OBJECTS = $(am_lift_filter_OBJECTS)
lift_filter_LDADD = $(LDADD)
lift_filter_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_merge_bsrate_OBJECTS = src/utils/merge-bsrate.$(OBJEXT)
merge_bsrate_OBJECTS = $(am_merge_bsrate_OBJECTS)
merge_bsrate_LDADD = $(LDADD)
merge_bsrate_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_merge_methcounts_OBJECTS = src/utils/merge-methcounts.$(OBJEXT)
merge_methcounts_OBJECTS = $(am_merge_methcounts_OBJECTS)
merge_methcounts_LDADD = $(LDADD)
merge_methcounts_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_methcounts_OBJECTS = src/analysis/methcounts.$(OBJEXT)
methcounts_OBJECTS = $(am_methcounts_OBJECTS)
methcounts_LDADD = $(LDADD)
methcounts_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_methdiff_OBJECTS = src/radmeth/methdiff.$(OBJEXT)
methdiff_OBJECTS = $(am_methdiff_OBJECTS)
methdiff_LDADD = $(LDADD)
methdiff_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_methentropy_OBJECTS = src/analysis/methentropy.$(OBJEXT)
methentropy_OBJECTS = $(am_methentropy_OBJECTS)
methentropy_LDADD = $(LDADD)
methentropy_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_methstates_OBJECTS = src/analysis/methstates.$(OBJEXT)
methstates_OBJECTS = $(am_methstates_OBJECTS)
methstates_LDADD = $(LDADD)
methstates_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_mlml_OBJECTS = src/mlml/mlml.$(OBJEXT)
mlml_OBJECTS = $(am_mlml_OBJECTS)
mlml_LDADD = $(LDADD)
mlml_DEPENDENCIES = libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a
am_multimethstat_OBJECTS = src/analysis/multimethstat.$(OBJEXT)
multimethstat_OBJECTS = $(am_multimethstat_OBJECTS)
multimethstat_LDADD = $(LDADD)
multimethstat_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_pmd_OBJECTS = src/analysis/pmd.$(OBJEXT)
pmd_OBJECTS = $(am_pmd_OBJECTS)
pmd_LDADD = $(LDADD)
pmd_DEPENDENCIES = libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a
am_radmeth_OBJECTS = src/radmeth/radmeth.$(OBJEXT) \
	src/radmeth/regression.$(OBJEXT) \
	src/radmeth/combine_pvals.$(OBJEXT)
radmeth_OBJECTS = $(am_radmeth_OBJECTS)
radmeth_LDADD = $(LDADD)
radmeth_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_roimethstat_OBJECTS = src/analysis/roimethstat.$(OBJEXT)
roimethstat_OBJECTS = $(am_roimethstat_OBJECTS)
roimethstat_LDADD = $(LDADD)
roimethstat_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_selectsites_OBJECTS = src/utils/selectsites.$(OBJEXT)
selectsites_OBJECTS = $(am_selectsites_OBJECTS)
selectsites_LDADD = $(LDADD)
selectsites_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_symmetric_cpgs_OBJECTS = src/utils/symmetric-cpgs.$(OBJEXT)
symmetric_cpgs_OBJECTS = $(am_symmetric_cpgs_OBJECTS)
symmetric_cpgs_LDADD = $(LDADD)
symmetric_cpgs_DEPENDENCIES = libmethpipe.a \
	src/smithlab_cpp/libsmithlab_cpp.a
am_to_mr_OBJECTS = src/utils/to-mr.$(OBJEXT)
to_mr_OBJECTS = $(am_to_mr_OBJECTS)
to_mr_LDADD = $(LDADD)
to_mr_DEPENDENCIES = libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = src/amrfinder/$(DEPDIR)/allelicmeth.Po \
	src/amrfinder/$(DEPDIR)/amrfinder.Po \
	src/amrfinder/$(DEPDIR)/amrtester.Po \
	src/analysis/$(DEPDIR)/bsrate.Po src/analysis/$(DEPDIR)/hmr.Po \
	src/analysis/$(DEPDIR)/hmr_rep.Po \
	src/analysis/$(DEPDIR)/hypermr.Po \
	src/analysis/$(DEPDIR)/levels.Po \
	src/analysis/$(DEPDIR)/methcounts.Po \
	src/analysis/$(DEPDIR)/methentropy.Po \
	src/analysis/$(DEPDIR)/methstates.Po \
	src/analysis/$(DEPDIR)/multimethstat.Po \
	src/analysis/$(DEPDIR)/pmd.Po \
	src/analysis/$(DEPDIR)/roimethstat.Po \
	src/common/$(DEPDIR)/BetaBin.Po src/common/$(DEPDIR)/Distro.Po \
	src/common/$(DEPDIR)/EmissionDistribution.Po \
	src/common/$(DEPDIR)/Epiread.Po \
	src/common/$(DEPDIR)/EpireadStats.Po \
	src/common/$(DEPDIR)/LevelsCounter.Po \
	src/common/$(DEPDIR)/MethpipeSite.Po \
	src/common/$(DEPDIR)/Smoothing.Po \
	src/common/$(DEPDIR)/ThreeStateHMM.Po \
	src/common/$(DEPDIR)/TwoStateHMM.Po \
	src/common/$(DEPDIR)/TwoStateHMM_PMD.Po \
	src/common/$(DEPDIR)/bsutils.Po \
	src/common/$(DEPDIR)/numerical_utils.Po \
	src/mlml/$(DEPDIR)/mlml.Po \
	src/radmeth/$(DEPDIR)/combine_pvals.Po \
	src/radmeth/$(DEPDIR)/dmr.Po src/radmeth/$(DEPDIR)/methdiff.Po \
	src/radmeth/$(DEPDIR)/radmeth.Po \
	src/radmeth/$(DEPDIR)/regression.Po \
	src/utils/$(DEPDIR)/clean-hairpins.Po \
	src/utils/$(DEPDIR)/duplicate-remover.Po \
	src/utils/$(DEPDIR)/fast-liftover.Po \
	src/utils/$(DEPDIR)/guessprotocol.Po \
	src/utils/$(DEPDIR)/lc_approx.Po \
	src/utils/$(DEPDIR)/lift-filter.Po \
	src/utils/$(DEPDIR)/merge-bsrate.Po \
	src/utils/$(DEPDIR)/merge-methcounts.Po \
	src/utils/$(DEPDIR)/selectsites.Po \
	src/utils/$(DEPDIR)/symmetric-cpgs.Po \
	src/utils/$(DEPDIR)/to-mr.Po
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libmethpipe_a_SOURCES) $(allelicmeth_SOURCES) \
	$(amrfinder_SOURCES) $(amrtester_SOURCES) $(bsrate_SOURCES) \
	$(clean_hairpins_SOURCES) $(dmr_SOURCES) \
	$(duplicate_remover_SOURCES) $(fast_liftover_SOURCES) \
	$(guessprotocol_SOURCES) $(hmr_SOURCES) $(hmr_rep_SOURCES) \
	$(hypermr_SOURCES) $(lc_approx_SOURCES) $(levels_SOURCES) \
	$(lift_filter_SOURCES) $(merge_bsrate_SOURCES) \
	$(merge_methcounts_SOURCES) $(methcounts_SOURCES) \
	$(methdiff_SOURCES) $(methentropy_SOURCES) \
	$(methstates_SOURCES) $(mlml_SOURCES) $(multimethstat_SOURCES) \
	$(pmd_SOURCES) $(radmeth_SOURCES) $(roimethstat_SOURCES) \
	$(selectsites_SOURCES) $(symmetric_cpgs_SOURCES) \
	$(to_mr_SOURCES)
DIST_SOURCES = $(libmethpipe_a_SOURCES) $(allelicmeth_SOURCES) \
	$(amrfinder_SOURCES) $(amrtester_SOURCES) $(bsrate_SOURCES) \
	$(clean_hairpins_SOURCES) $(dmr_SOURCES) \
	$(duplicate_remover_SOURCES) $(fast_liftover_SOURCES) \
	$(guessprotocol_SOURCES) $(hmr_SOURCES) $(hmr_rep_SOURCES) \
	$(hypermr_SOURCES) $(lc_approx_SOURCES) $(levels_SOURCES) \
	$(lift_filter_SOURCES) $(merge_bsrate_SOURCES) \
	$(merge_methcounts_SOURCES) $(methcounts_SOURCES) \
	$(methdiff_SOURCES) $(methentropy_SOURCES) \
	$(methstates_SOURCES) $(mlml_SOURCES) $(multimethstat_SOURCES) \
	$(pmd_SOURCES) $(radmeth_SOURCES) $(roimethstat_SOURCES) \
	$(selectsites_SOURCES) $(symmetric_cpgs_SOURCES) \
	$(to_mr_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir distdir-am dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in depcomp \
	install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/sena/methpipe/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AUTOCONF = ${SHELL} /home/sena/methpipe/missing autoconf
AUTOHEADER = ${SHELL} /home/sena/methpipe/missing autoheader
AUTOMAKE = ${SHELL} /home/sena/methpipe/missing automake-1.16
AWK = gawk
CPPFLAGS = 
CXX = g++ -std=c++11
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -O3 # default has optimization on
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
HAVE_CXX11 = 1
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lgsl -lgslcblas -lz 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/sena/methpipe/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = methpipe
PACKAGE_BUGREPORT = andrewds@usc.edu
PACKAGE_NAME = methpipe
PACKAGE_STRING = methpipe 4.1.1
PACKAGE_TARNAME = methpipe
PACKAGE_URL = https://github.com/smithlabcode/methpipe
PACKAGE_VERSION = 4.1.1
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 4.1.1
abs_builddir = /home/sena/methpipe
abs_srcdir = /home/sena/methpipe
abs_top_builddir = /home/sena/methpipe
abs_top_srcdir = /home/sena/methpipe
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/sena/methpipe/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /home/sena/methpipe
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
subdirs =  src/smithlab_cpp
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
EXTRA_DIST = README.md
ACLOCAL_AMFLAGS = -I m4
SUBDIRS := src/smithlab_cpp
AM_CPPFLAGS = -I $(top_srcdir)/src/common -I $(top_srcdir)/src/smithlab_cpp
noinst_LIBRARIES = libmethpipe.a
libmethpipe_a_SOURCES = src/common/BetaBin.cpp src/common/Distro.cpp \
	src/common/EmissionDistribution.cpp src/common/Epiread.cpp \
	src/common/EpireadStats.cpp src/common/LevelsCounter.cpp \
	src/common/MethpipeSite.cpp src/common/Smoothing.cpp \
	src/common/ThreeStateHMM.cpp src/common/TwoStateHMM.cpp \
	src/common/TwoStateHMM_PMD.cpp src/common/bsutils.cpp \
	src/common/numerical_utils.cpp src/common/BetaBin.hpp \
	src/common/Distro.hpp src/common/EmissionDistribution.hpp \
	src/common/Epiread.hpp src/common/EpireadStats.hpp \
	src/common/LevelsCounter.hpp src/common/MethpipeFiles.hpp \
	src/common/MethpipeSite.hpp src/common/Smoothing.hpp \
	src/common/ThreeStateHMM.hpp src/common/TwoStateHMM.hpp \
	src/common/TwoStateHMM_PMD.hpp src/common/bsutils.hpp \
	src/common/numerical_utils.hpp
LDADD = libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a
pmd_SOURCES = src/analysis/pmd.cpp
methstates_SOURCES = src/analysis/methstates.cpp
bsrate_SOURCES = src/analysis/bsrate.cpp
methentropy_SOURCES = src/analysis/methentropy.cpp
methcounts_SOURCES = src/analysis/methcounts.cpp
roimethstat_SOURCES = src/analysis/roimethstat.cpp
multimethstat_SOURCES = src/analysis/multimethstat.cpp
hmr_SOURCES = src/analysis/hmr.cpp
hmr_rep_SOURCES = src/analysis/hmr_rep.cpp
levels_SOURCES = src/analysis/levels.cpp
hypermr_SOURCES = src/analysis/hypermr.cpp
clean_hairpins_SOURCES = src/utils/clean-hairpins.cpp
guessprotocol_SOURCES = src/utils/guessprotocol.cpp
duplicate_remover_SOURCES = src/utils/duplicate-remover.cpp
merge_bsrate_SOURCES = src/utils/merge-bsrate.cpp
to_mr_SOURCES = src/utils/to-mr.cpp
lc_approx_SOURCES = src/utils/lc_approx.cpp
selectsites_SOURCES = src/utils/selectsites.cpp
symmetric_cpgs_SOURCES = src/utils/symmetric-cpgs.cpp
merge_methcounts_SOURCES = src/utils/merge-methcounts.cpp
lift_filter_SOURCES = src/utils/lift-filter.cpp
fast_liftover_SOURCES = src/utils/fast-liftover.cpp
allelicmeth_SOURCES = src/amrfinder/allelicmeth.cpp
amrfinder_SOURCES = src/amrfinder/amrfinder.cpp
amrtester_SOURCES = src/amrfinder/amrtester.cpp
dmr_SOURCES = src/radmeth/dmr.cpp
methdiff_SOURCES = src/radmeth/methdiff.cpp
radmeth_SOURCES = src/radmeth/radmeth.cpp src/radmeth/regression.cpp \
	src/radmeth/combine_pvals.cpp src/radmeth/regression.hpp \
	src/radmeth/combine_pvals.hpp src/radmeth/merge.hpp
mlml_SOURCES = src/mlml/mlml.cpp
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
src/common/$(am__dirstamp):
	@$(MKDIR_P) src/common
	@: > src/common/$(am__dirstamp)
src/common/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/common/$(DEPDIR)
	@: > src/common/$(DEPDIR)/$(am__dirstamp)
src/common/BetaBin.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/Distro.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/EmissionDistribution.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/Epiread.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/EpireadStats.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/LevelsCounter.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/MethpipeSite.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/Smoothing.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/ThreeStateHMM.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/TwoStateHMM.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/TwoStateHMM_PMD.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/bsutils.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)
src/common/numerical_utils.$(OBJEXT): src/common/$(am__dirstamp) \
	src/common/$(DEPDIR)/$(am__dirstamp)

libmethpipe.a: $(libmethpipe_a_OBJECTS) $(libmethpipe_a_DEPENDENCIES) $(EXTRA_libmethpipe_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f libmethpipe.a
	$(AM_V_AR)$(libmethpipe_a_AR) libmethpipe.a $(libmethpipe_a_OBJECTS) $(libmethpipe_a_LIBADD)
	$(AM_V_at)$(RANLIB) libmethpipe.a
src/amrfinder/$(am__dirstamp):
	@$(MKDIR_P) src/amrfinder
	@: > src/amrfinder/$(am__dirstamp)
src/amrfinder/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/amrfinder/$(DEPDIR)
	@: > src/amrfinder/$(DEPDIR)/$(am__dirstamp)
src/amrfinder/allelicmeth.$(OBJEXT): src/amrfinder/$(am__dirstamp) \
	src/amrfinder/$(DEPDIR)/$(am__dirstamp)

allelicmeth$(EXEEXT): $(allelicmeth_OBJECTS) $(allelicmeth_DEPENDENCIES) $(EXTRA_allelicmeth_DEPENDENCIES) 
	@rm -f allelicmeth$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(allelicmeth_OBJECTS) $(allelicmeth_LDADD) $(LIBS)
src/amrfinder/amrfinder.$(OBJEXT): src/amrfinder/$(am__dirstamp) \
	src/amrfinder/$(DEPDIR)/$(am__dirstamp)

amrfinder$(EXEEXT): $(amrfinder_OBJECTS) $(amrfinder_DEPENDENCIES) $(EXTRA_amrfinder_DEPENDENCIES) 
	@rm -f amrfinder$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(amrfinder_OBJECTS) $(amrfinder_LDADD) $(LIBS)
src/amrfinder/amrtester.$(OBJEXT): src/amrfinder/$(am__dirstamp) \
	src/amrfinder/$(DEPDIR)/$(am__dirstamp)

amrtester$(EXEEXT): $(amrtester_OBJECTS) $(amrtester_DEPENDENCIES) $(EXTRA_amrtester_DEPENDENCIES) 
	@rm -f amrtester$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(amrtester_OBJECTS) $(amrtester_LDADD) $(LIBS)
src/analysis/$(am__dirstamp):
	@$(MKDIR_P) src/analysis
	@: > src/analysis/$(am__dirstamp)
src/analysis/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/analysis/$(DEPDIR)
	@: > src/analysis/$(DEPDIR)/$(am__dirstamp)
src/analysis/bsrate.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

bsrate$(EXEEXT): $(bsrate_OBJECTS) $(bsrate_DEPENDENCIES) $(EXTRA_bsrate_DEPENDENCIES) 
	@rm -f bsrate$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(bsrate_OBJECTS) $(bsrate_LDADD) $(LIBS)
src/utils/$(am__dirstamp):
	@$(MKDIR_P) src/utils
	@: > src/utils/$(am__dirstamp)
src/utils/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/utils/$(DEPDIR)
	@: > src/utils/$(DEPDIR)/$(am__dirstamp)
src/utils/clean-hairpins.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

clean-hairpins$(EXEEXT): $(clean_hairpins_OBJECTS) $(clean_hairpins_DEPENDENCIES) $(EXTRA_clean_hairpins_DEPENDENCIES) 
	@rm -f clean-hairpins$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(clean_hairpins_OBJECTS) $(clean_hairpins_LDADD) $(LIBS)
src/radmeth/$(am__dirstamp):
	@$(MKDIR_P) src/radmeth
	@: > src/radmeth/$(am__dirstamp)
src/radmeth/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/radmeth/$(DEPDIR)
	@: > src/radmeth/$(DEPDIR)/$(am__dirstamp)
src/radmeth/dmr.$(OBJEXT): src/radmeth/$(am__dirstamp) \
	src/radmeth/$(DEPDIR)/$(am__dirstamp)

dmr$(EXEEXT): $(dmr_OBJECTS) $(dmr_DEPENDENCIES) $(EXTRA_dmr_DEPENDENCIES) 
	@rm -f dmr$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(dmr_OBJECTS) $(dmr_LDADD) $(LIBS)
src/utils/duplicate-remover.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

duplicate-remover$(EXEEXT): $(duplicate_remover_OBJECTS) $(duplicate_remover_DEPENDENCIES) $(EXTRA_duplicate_remover_DEPENDENCIES) 
	@rm -f duplicate-remover$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(duplicate_remover_OBJECTS) $(duplicate_remover_LDADD) $(LIBS)
src/utils/fast-liftover.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

fast-liftover$(EXEEXT): $(fast_liftover_OBJECTS) $(fast_liftover_DEPENDENCIES) $(EXTRA_fast_liftover_DEPENDENCIES) 
	@rm -f fast-liftover$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(fast_liftover_OBJECTS) $(fast_liftover_LDADD) $(LIBS)
src/utils/guessprotocol.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

guessprotocol$(EXEEXT): $(guessprotocol_OBJECTS) $(guessprotocol_DEPENDENCIES) $(EXTRA_guessprotocol_DEPENDENCIES) 
	@rm -f guessprotocol$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(guessprotocol_OBJECTS) $(guessprotocol_LDADD) $(LIBS)
src/analysis/hmr.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

hmr$(EXEEXT): $(hmr_OBJECTS) $(hmr_DEPENDENCIES) $(EXTRA_hmr_DEPENDENCIES) 
	@rm -f hmr$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(hmr_OBJECTS) $(hmr_LDADD) $(LIBS)
src/analysis/hmr_rep.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

hmr_rep$(EXEEXT): $(hmr_rep_OBJECTS) $(hmr_rep_DEPENDENCIES) $(EXTRA_hmr_rep_DEPENDENCIES) 
	@rm -f hmr_rep$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(hmr_rep_OBJECTS) $(hmr_rep_LDADD) $(LIBS)
src/analysis/hypermr.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

hypermr$(EXEEXT): $(hypermr_OBJECTS) $(hypermr_DEPENDENCIES) $(EXTRA_hypermr_DEPENDENCIES) 
	@rm -f hypermr$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(hypermr_OBJECTS) $(hypermr_LDADD) $(LIBS)
src/utils/lc_approx.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

lc_approx$(EXEEXT): $(lc_approx_OBJECTS) $(lc_approx_DEPENDENCIES) $(EXTRA_lc_approx_DEPENDENCIES) 
	@rm -f lc_approx$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(lc_approx_OBJECTS) $(lc_approx_LDADD) $(LIBS)
src/analysis/levels.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

levels$(EXEEXT): $(levels_OBJECTS) $(levels_DEPENDENCIES) $(EXTRA_levels_DEPENDENCIES) 
	@rm -f levels$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(levels_OBJECTS) $(levels_LDADD) $(LIBS)
src/utils/lift-filter.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

lift-filter$(EXEEXT): $(lift_filter_OBJECTS) $(lift_filter_DEPENDENCIES) $(EXTRA_lift_filter_DEPENDENCIES) 
	@rm -f lift-filter$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(lift_filter_OBJECTS) $(lift_filter_LDADD) $(LIBS)
src/utils/merge-bsrate.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

merge-bsrate$(EXEEXT): $(merge_bsrate_OBJECTS) $(merge_bsrate_DEPENDENCIES) $(EXTRA_merge_bsrate_DEPENDENCIES) 
	@rm -f merge-bsrate$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(merge_bsrate_OBJECTS) $(merge_bsrate_LDADD) $(LIBS)
src/utils/merge-methcounts.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

merge-methcounts$(EXEEXT): $(merge_methcounts_OBJECTS) $(merge_methcounts_DEPENDENCIES) $(EXTRA_merge_methcounts_DEPENDENCIES) 
	@rm -f merge-methcounts$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(merge_methcounts_OBJECTS) $(merge_methcounts_LDADD) $(LIBS)
src/analysis/methcounts.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

methcounts$(EXEEXT): $(methcounts_OBJECTS) $(methcounts_DEPENDENCIES) $(EXTRA_methcounts_DEPENDENCIES) 
	@rm -f methcounts$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(methcounts_OBJECTS) $(methcounts_LDADD) $(LIBS)
src/radmeth/methdiff.$(OBJEXT): src/radmeth/$(am__dirstamp) \
	src/radmeth/$(DEPDIR)/$(am__dirstamp)

methdiff$(EXEEXT): $(methdiff_OBJECTS) $(methdiff_DEPENDENCIES) $(EXTRA_methdiff_DEPENDENCIES) 
	@rm -f methdiff$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(methdiff_OBJECTS) $(methdiff_LDADD) $(LIBS)
src/analysis/methentropy.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

methentropy$(EXEEXT): $(methentropy_OBJECTS) $(methentropy_DEPENDENCIES) $(EXTRA_methentropy_DEPENDENCIES) 
	@rm -f methentropy$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(methentropy_OBJECTS) $(methentropy_LDADD) $(LIBS)
src/analysis/methstates.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

methstates$(EXEEXT): $(methstates_OBJECTS) $(methstates_DEPENDENCIES) $(EXTRA_methstates_DEPENDENCIES) 
	@rm -f methstates$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(methstates_OBJECTS) $(methstates_LDADD) $(LIBS)
src/mlml/$(am__dirstamp):
	@$(MKDIR_P) src/mlml
	@: > src/mlml/$(am__dirstamp)
src/mlml/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/mlml/$(DEPDIR)
	@: > src/mlml/$(DEPDIR)/$(am__dirstamp)
src/mlml/mlml.$(OBJEXT): src/mlml/$(am__dirstamp) \
	src/mlml/$(DEPDIR)/$(am__dirstamp)

mlml$(EXEEXT): $(mlml_OBJECTS) $(mlml_DEPENDENCIES) $(EXTRA_mlml_DEPENDENCIES) 
	@rm -f mlml$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(mlml_OBJECTS) $(mlml_LDADD) $(LIBS)
src/analysis/multimethstat.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

multimethstat$(EXEEXT): $(multimethstat_OBJECTS) $(multimethstat_DEPENDENCIES) $(EXTRA_multimethstat_DEPENDENCIES) 
	@rm -f multimethstat$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(multimethstat_OBJECTS) $(multimethstat_LDADD) $(LIBS)
src/analysis/pmd.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

pmd$(EXEEXT): $(pmd_OBJECTS) $(pmd_DEPENDENCIES) $(EXTRA_pmd_DEPENDENCIES) 
	@rm -f pmd$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(pmd_OBJECTS) $(pmd_LDADD) $(LIBS)
src/radmeth/radmeth.$(OBJEXT): src/radmeth/$(am__dirstamp) \
	src/radmeth/$(DEPDIR)/$(am__dirstamp)
src/radmeth/regression.$(OBJEXT): src/radmeth/$(am__dirstamp) \
	src/radmeth/$(DEPDIR)/$(am__dirstamp)
src/radmeth/combine_pvals.$(OBJEXT): src/radmeth/$(am__dirstamp) \
	src/radmeth/$(DEPDIR)/$(am__dirstamp)

radmeth$(EXEEXT): $(radmeth_OBJECTS) $(radmeth_DEPENDENCIES) $(EXTRA_radmeth_DEPENDENCIES) 
	@rm -f radmeth$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(radmeth_OBJECTS) $(radmeth_LDADD) $(LIBS)
src/analysis/roimethstat.$(OBJEXT): src/analysis/$(am__dirstamp) \
	src/analysis/$(DEPDIR)/$(am__dirstamp)

roimethstat$(EXEEXT): $(roimethstat_OBJECTS) $(roimethstat_DEPENDENCIES) $(EXTRA_roimethstat_DEPENDENCIES) 
	@rm -f roimethstat$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(roimethstat_OBJECTS) $(roimethstat_LDADD) $(LIBS)
src/utils/selectsites.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

selectsites$(EXEEXT): $(selectsites_OBJECTS) $(selectsites_DEPENDENCIES) $(EXTRA_selectsites_DEPENDENCIES) 
	@rm -f selectsites$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(selectsites_OBJECTS) $(selectsites_LDADD) $(LIBS)
src/utils/symmetric-cpgs.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

symmetric-cpgs$(EXEEXT): $(symmetric_cpgs_OBJECTS) $(symmetric_cpgs_DEPENDENCIES) $(EXTRA_symmetric_cpgs_DEPENDENCIES) 
	@rm -f symmetric-cpgs$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(symmetric_cpgs_OBJECTS) $(symmetric_cpgs_LDADD) $(LIBS)
src/utils/to-mr.$(OBJEXT): src/utils/$(am__dirstamp) \
	src/utils/$(DEPDIR)/$(am__dirstamp)

to-mr$(EXEEXT): $(to_mr_OBJECTS) $(to_mr_DEPENDENCIES) $(EXTRA_to_mr_DEPENDENCIES) 
	@rm -f to-mr$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(to_mr_OBJECTS) $(to_mr_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/amrfinder/*.$(OBJEXT)
	-rm -f src/analysis/*.$(OBJEXT)
	-rm -f src/common/*.$(OBJEXT)
	-rm -f src/mlml/*.$(OBJEXT)
	-rm -f src/radmeth/*.$(OBJEXT)
	-rm -f src/utils/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/amrfinder/$(DEPDIR)/allelicmeth.Po # am--include-marker
include src/amrfinder/$(DEPDIR)/amrfinder.Po # am--include-marker
include src/amrfinder/$(DEPDIR)/amrtester.Po # am--include-marker
include src/analysis/$(DEPDIR)/bsrate.Po # am--include-marker
include src/analysis/$(DEPDIR)/hmr.Po # am--include-marker
include src/analysis/$(DEPDIR)/hmr_rep.Po # am--include-marker
include src/analysis/$(DEPDIR)/hypermr.Po # am--include-marker
include src/analysis/$(DEPDIR)/levels.Po # am--include-marker
include src/analysis/$(DEPDIR)/methcounts.Po # am--include-marker
include src/analysis/$(DEPDIR)/methentropy.Po # am--include-marker
include src/analysis/$(DEPDIR)/methstates.Po # am--include-marker
include src/analysis/$(DEPDIR)/multimethstat.Po # am--include-marker
include src/analysis/$(DEPDIR)/pmd.Po # am--include-marker
include src/analysis/$(DEPDIR)/roimethstat.Po # am--include-marker
include src/common/$(DEPDIR)/BetaBin.Po # am--include-marker
include src/common/$(DEPDIR)/Distro.Po # am--include-marker
include src/common/$(DEPDIR)/EmissionDistribution.Po # am--include-marker
include src/common/$(DEPDIR)/Epiread.Po # am--include-marker
include src/common/$(DEPDIR)/EpireadStats.Po # am--include-marker
include src/common/$(DEPDIR)/LevelsCounter.Po # am--include-marker
include src/common/$(DEPDIR)/MethpipeSite.Po # am--include-marker
include src/common/$(DEPDIR)/Smoothing.Po # am--include-marker
include src/common/$(DEPDIR)/ThreeStateHMM.Po # am--include-marker
include src/common/$(DEPDIR)/TwoStateHMM.Po # am--include-marker
include src/common/$(DEPDIR)/TwoStateHMM_PMD.Po # am--include-marker
include src/common/$(DEPDIR)/bsutils.Po # am--include-marker
include src/common/$(DEPDIR)/numerical_utils.Po # am--include-marker
include src/mlml/$(DEPDIR)/mlml.Po # am--include-marker
include src/radmeth/$(DEPDIR)/combine_pvals.Po # am--include-marker
include src/radmeth/$(DEPDIR)/dmr.Po # am--include-marker
include src/radmeth/$(DEPDIR)/methdiff.Po # am--include-marker
include src/radmeth/$(DEPDIR)/radmeth.Po # am--include-marker
include src/radmeth/$(DEPDIR)/regression.Po # am--include-marker
include src/utils/$(DEPDIR)/clean-hairpins.Po # am--include-marker
include src/utils/$(DEPDIR)/duplicate-remover.Po # am--include-marker
include src/utils/$(DEPDIR)/fast-liftover.Po # am--include-marker
include src/utils/$(DEPDIR)/guessprotocol.Po # am--include-marker
include src/utils/$(DEPDIR)/lc_approx.Po # am--include-marker
include src/utils/$(DEPDIR)/lift-filter.Po # am--include-marker
include src/utils/$(DEPDIR)/merge-bsrate.Po # am--include-marker
include src/utils/$(DEPDIR)/merge-methcounts.Po # am--include-marker
include src/utils/$(DEPDIR)/selectsites.Po # am--include-marker
include src/utils/$(DEPDIR)/symmetric-cpgs.Po # am--include-marker
include src/utils/$(DEPDIR)/to-mr.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(LIBRARIES) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/amrfinder/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/amrfinder/$(am__dirstamp)
	-rm -f src/analysis/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/analysis/$(am__dirstamp)
	-rm -f src/common/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/common/$(am__dirstamp)
	-rm -f src/mlml/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/mlml/$(am__dirstamp)
	-rm -f src/radmeth/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/radmeth/$(am__dirstamp)
	-rm -f src/utils/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/utils/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-noinstLIBRARIES \
	mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f src/amrfinder/$(DEPDIR)/allelicmeth.Po
	-rm -f src/amrfinder/$(DEPDIR)/amrfinder.Po
	-rm -f src/amrfinder/$(DEPDIR)/amrtester.Po
	-rm -f src/analysis/$(DEPDIR)/bsrate.Po
	-rm -f src/analysis/$(DEPDIR)/hmr.Po
	-rm -f src/analysis/$(DEPDIR)/hmr_rep.Po
	-rm -f src/analysis/$(DEPDIR)/hypermr.Po
	-rm -f src/analysis/$(DEPDIR)/levels.Po
	-rm -f src/analysis/$(DEPDIR)/methcounts.Po
	-rm -f src/analysis/$(DEPDIR)/methentropy.Po
	-rm -f src/analysis/$(DEPDIR)/methstates.Po
	-rm -f src/analysis/$(DEPDIR)/multimethstat.Po
	-rm -f src/analysis/$(DEPDIR)/pmd.Po
	-rm -f src/analysis/$(DEPDIR)/roimethstat.Po
	-rm -f src/common/$(DEPDIR)/BetaBin.Po
	-rm -f src/common/$(DEPDIR)/Distro.Po
	-rm -f src/common/$(DEPDIR)/EmissionDistribution.Po
	-rm -f src/common/$(DEPDIR)/Epiread.Po
	-rm -f src/common/$(DEPDIR)/EpireadStats.Po
	-rm -f src/common/$(DEPDIR)/LevelsCounter.Po
	-rm -f src/common/$(DEPDIR)/MethpipeSite.Po
	-rm -f src/common/$(DEPDIR)/Smoothing.Po
	-rm -f src/common/$(DEPDIR)/ThreeStateHMM.Po
	-rm -f src/common/$(DEPDIR)/TwoStateHMM.Po
	-rm -f src/common/$(DEPDIR)/TwoStateHMM_PMD.Po
	-rm -f src/common/$(DEPDIR)/bsutils.Po
	-rm -f src/common/$(DEPDIR)/numerical_utils.Po
	-rm -f src/mlml/$(DEPDIR)/mlml.Po
	-rm -f src/radmeth/$(DEPDIR)/combine_pvals.Po
	-rm -f src/radmeth/$(DEPDIR)/dmr.Po
	-rm -f src/radmeth/$(DEPDIR)/methdiff.Po
	-rm -f src/radmeth/$(DEPDIR)/radmeth.Po
	-rm -f src/radmeth/$(DEPDIR)/regression.Po
	-rm -f src/utils/$(DEPDIR)/clean-hairpins.Po
	-rm -f src/utils/$(DEPDIR)/duplicate-remover.Po
	-rm -f src/utils/$(DEPDIR)/fast-liftover.Po
	-rm -f src/utils/$(DEPDIR)/guessprotocol.Po
	-rm -f src/utils/$(DEPDIR)/lc_approx.Po
	-rm -f src/utils/$(DEPDIR)/lift-filter.Po
	-rm -f src/utils/$(DEPDIR)/merge-bsrate.Po
	-rm -f src/utils/$(DEPDIR)/merge-methcounts.Po
	-rm -f src/utils/$(DEPDIR)/selectsites.Po
	-rm -f src/utils/$(DEPDIR)/symmetric-cpgs.Po
	-rm -f src/utils/$(DEPDIR)/to-mr.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f src/amrfinder/$(DEPDIR)/allelicmeth.Po
	-rm -f src/amrfinder/$(DEPDIR)/amrfinder.Po
	-rm -f src/amrfinder/$(DEPDIR)/amrtester.Po
	-rm -f src/analysis/$(DEPDIR)/bsrate.Po
	-rm -f src/analysis/$(DEPDIR)/hmr.Po
	-rm -f src/analysis/$(DEPDIR)/hmr_rep.Po
	-rm -f src/analysis/$(DEPDIR)/hypermr.Po
	-rm -f src/analysis/$(DEPDIR)/levels.Po
	-rm -f src/analysis/$(DEPDIR)/methcounts.Po
	-rm -f src/analysis/$(DEPDIR)/methentropy.Po
	-rm -f src/analysis/$(DEPDIR)/methstates.Po
	-rm -f src/analysis/$(DEPDIR)/multimethstat.Po
	-rm -f src/analysis/$(DEPDIR)/pmd.Po
	-rm -f src/analysis/$(DEPDIR)/roimethstat.Po
	-rm -f src/common/$(DEPDIR)/BetaBin.Po
	-rm -f src/common/$(DEPDIR)/Distro.Po
	-rm -f src/common/$(DEPDIR)/EmissionDistribution.Po
	-rm -f src/common/$(DEPDIR)/Epiread.Po
	-rm -f src/common/$(DEPDIR)/EpireadStats.Po
	-rm -f src/common/$(DEPDIR)/LevelsCounter.Po
	-rm -f src/common/$(DEPDIR)/MethpipeSite.Po
	-rm -f src/common/$(DEPDIR)/Smoothing.Po
	-rm -f src/common/$(DEPDIR)/ThreeStateHMM.Po
	-rm -f src/common/$(DEPDIR)/TwoStateHMM.Po
	-rm -f src/common/$(DEPDIR)/TwoStateHMM_PMD.Po
	-rm -f src/common/$(DEPDIR)/bsutils.Po
	-rm -f src/common/$(DEPDIR)/numerical_utils.Po
	-rm -f src/mlml/$(DEPDIR)/mlml.Po
	-rm -f src/radmeth/$(DEPDIR)/combine_pvals.Po
	-rm -f src/radmeth/$(DEPDIR)/dmr.Po
	-rm -f src/radmeth/$(DEPDIR)/methdiff.Po
	-rm -f src/radmeth/$(DEPDIR)/radmeth.Po
	-rm -f src/radmeth/$(DEPDIR)/regression.Po
	-rm -f src/utils/$(DEPDIR)/clean-hairpins.Po
	-rm -f src/utils/$(DEPDIR)/duplicate-remover.Po
	-rm -f src/utils/$(DEPDIR)/fast-liftover.Po
	-rm -f src/utils/$(DEPDIR)/guessprotocol.Po
	-rm -f src/utils/$(DEPDIR)/lc_approx.Po
	-rm -f src/utils/$(DEPDIR)/lift-filter.Po
	-rm -f src/utils/$(DEPDIR)/merge-bsrate.Po
	-rm -f src/utils/$(DEPDIR)/merge-methcounts.Po
	-rm -f src/utils/$(DEPDIR)/selectsites.Po
	-rm -f src/utils/$(DEPDIR)/symmetric-cpgs.Po
	-rm -f src/utils/$(DEPDIR)/to-mr.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: $(am__recursive_targets) all install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--depfiles am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic \
	clean-noinstLIBRARIES cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile

install installdirs: SUBDIRS := $(filter-out src/smithlab_cpp, $(SUBDIRS))

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
