#!/usr/bin/env python

import sys, os.path, bz2
from optparse import OptionParser

def stripBzipSuff(s):
    if s[-4:] == '.bz2': return s[:-4]
    else: return s

def isBzipFile(fn):
    return os.path.splitext(fn)[-1] == '.bz2'

def linecount(fn):
    f = open(fn)
    if isBzipFile(fn):
        f.close()
        f = bz2.BZ2File(fn)
    lines = 0
    for i in f: lines += 1
    f.close()
    return lines

def goodFileName(fn, querySuff):
    path, suff = os.path.splitext(stripBzipSuff(fn))
    return suff[1:] == querySuff
        
def main(argv):                         

    usage = "usage: %prog [options]"
    parser = OptionParser(usage=usage)
    parser.add_option("-o", action="store", type="string",
                      dest="outFile", help="output file", metavar="<filename>")
    parser.add_option("-f", action="store", type="string", dest="filename",
                      help="reads file to count", metavar="<filename>")
    
    (opt, args) = parser.parse_args(argv)
    if opt.filename == None:
        parser.print_help()
        sys.exit(1)
    
    out = sys.stdout
    if opt.outFile != None:
        out = open(opt.outFile, 'w')

    currCount = int(linecount(os.path.abspath(opt.filename))/4.0)
    out.write('%s\t%d\n' % (os.path.basename(opt.filename), currCount))
    out.close()
    
if __name__ == "__main__":
    main(sys.argv)
