#!/bin/bash

# Copyright (C) 2014 University of Southern California
# Authors: Benjamin Decato, Andrew D. Smith
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with This program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

BINPATH=$1 
CHROMS=$2 
BASE_NAME=$3

if [[ ! -d "$BINPATH" || ! -d "$CHROMS" ]]
then
    echo "Please specify a valid path to methpipe binaries and chroms dir."
    exit
fi

LC_ALL=C

sort -k 1,1 -k 2,2g -k 3,3g -k 6,6 -o ${BASE_NAME}.mr.sorted ${BASE_NAME}.mr
mv ${BASE_NAME}.mr.sorted ${BASE_NAME}.mr

#### COMMENT DUPLICATE REMOVAL BELOW IF RRBS
${BINPATH}/duplicate-remover -S ${BASE_NAME}.stats \
    -o ${BASE_NAME}.mr.uniq ${BASE_NAME}.mr

${BINPATH}/bsrate -c ${CHROMS} -o ${BASE_NAME}.bsrate ${BASE_NAME}.mr.uniq
${BINPATH}/methcounts -c ${CHROMS} -S ${BASE_NAME}.methstats \
    -o ${BASE_NAME}.meth ${BASE_NAME}.mr.uniq
${BINPATH}/levels -o ${BASE_NAME}.levels ${BASE_NAME}.meth
${BINPATH}/methstates -c ${CHROMS} -o ${BASE_NAME}.epiread ${BASE_NAME}.mr.uniq

rm ${BASE_NAME}.mr.uniq
