#!/bin/bash

# Copyright (C) 2012 University of Southern California
# Authors: Benjamin Decato, Andrew D. Smith
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with This program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

BINPATH=$1 
CHROMS=$2 
BASE_NAME=$3
LIB_OR_REP=$4

if [[ ! -d "${BINPATH}" || ! -d "${CHROMS}" ]]
then
    echo "Please specify a valid path to methpipe binaries and chroms dir."
    exit
fi

LC_ALL=C

${BINPATH}/merge-methcounts -o ${BASE_NAME}.meth ../${BASE_NAME}_${LIB_OR_REP}*/$(basename $PWD)/*.meth
${BINPATH}/hmr -p ${BASE_NAME}.params -o ${BASE_NAME}.hmr ${BASE_NAME}.meth
${BINPATH}/hmr -partial -o ${BASE_NAME}.pmd ${BASE_NAME}.meth
${BINPATH}/levels -o ${BASE_NAME}.levels ${BASE_NAME}.meth

sort -m -k 1,1 -k 2,2g -k 3,3g -k 6,6 -o ${BASE_NAME}.states \
    ../${BASE_NAME}_${LIB_OR_REP}*/$(basename $PWD)/*.states
${BINPATH}/allelicmeth -c ${CHROMS} -o ${BASE_NAME}.allelicmeth ${BASE_NAME}.states
${BINPATH}/amrfinder -v -o ${BASE_NAME}.amr -i 10 -w 10 -m 1 -c ${CHROMS} -E ${BASE_NAME}.states

# TODO: bsrate merging program
